#!/bin/bash
# This script calls SeaDisplayTool to create a distribution, average or
# standard deviation plot for each "RDL*" folder in the "INPUTFOLDER" directory.
# If you use weekly or monthly archive folders for radials, the result is 
# weekly or monthly plots.
# If the given "INPUTFOLDER" has "RDL*" files in it instead of archive folders, 
# a plot will be created for each individual file.
# If you would like to change plot settings, make the changes to the map in
# SeaDisplay and it should update the plist file that is used by SeaDisplayTool.
#
# Inputs are 
# 1) four letter site code
# 2) input directory
# 3) output directory 
# 4) plot type (distribution, average or stddev)
# 5) prefix to use with output files 
# Example: seadisplaytool_plots VIEW /Codar/SeaSonde/Archives/Radials/ 
#  /Codar/SeaSonde/Users/Distribution/ distribution DIST

SITE=$1
INPUTFOLDER=$2
OUTFOLDER=$3

mkdir $OUTFOLDER

cd $INPUTFOLDER
shopt -s nullglob
for f in $SITE_RDL*; do
/Codar/SeaSonde/Apps/Bin/SeaDisplayTool -i=${INPUTFOLDER}${f} -o=${OUTFOLDER}/$5_${f}.jpeg -$4 -imageformat="JPEG" -imagedepth=32 -showtext -site=${SITE}
done
